# 1. GENERAR DATASET

In [1]:
import pandas as pd
import glob
import os

ruta = "PV_MaximumPowerPredictor/*.csv"

dfs = []

for archivo in glob.glob(ruta):
    
    nombre = os.path.basename(archivo).replace(".csv","")
    
    partes = nombre.split("_")
    
    parque_id = partes[0]              # Cocoa / Golden / Eugene
    panel_id = "_".join(partes[1:])    # tipo de panel
    
    df = pd.read_csv(archivo)
    
    # eliminar timestamp
    df = df.drop(columns=["Time Stamp (local standard time) yyyy-mm-ddThh:mm:ss"], errors="ignore")
    
    # añadir columnas
    df["parque_id"] = parque_id
    df["panel_id"] = panel_id
    
    # mover columnas al inicio
    cols = ["parque_id","panel_id"] + [c for c in df.columns if c not in ["parque_id","panel_id"]]
    df = df[cols]
    
    dfs.append(df)

dataset_total = pd.concat(dfs, ignore_index=True)

print(dataset_total.shape)
dataset_total.head()

(1025599, 12)

,parque_id,panel_id,POA irradiance CMP22 pyranometer (W/m2),PV module back surface temperature (degC),Pmp (W),Dry bulb temperature (degC),Relative humidity (%RH),Atmospheric pressure (mb),Precipitation (mm) accumulated daily total,Direct normal irradiance (W/m2),Global horizontal irradiance (W/m2),Diffuse horizontal irradiance (W/m2)
0,Cocoa,aSiMicro03036_cleaned,20.2,19.3,1.9610,17.7,96.0,1009.8,20.3,0.1,21.9,22.2
1,Cocoa,aSiMicro03036_cleaned,35.8,19.5,3.7242,17.8,96.0,1009.7,20.3,0.1,38.4,39.0
2,Cocoa,aSiMicro03036_cleaned,20.2,19.5,1.9551,17.8,96.0,1009.9,20.3,0.1,20.1,20.3
3,Cocoa,aSiMicro03036_cleaned,20.6,19.5,2.0057,17.8,96.1,1009.8,20.3,0.1,21.4,21.8
4,Cocoa,aSiMicro03036_cleaned,29.5,19.5,3.1397,17.8,96.0,1009.9,20.6,0.1,29.3,29.5

# 2. EXPLORAR LOS DATOS

In [2]:
dataset_total["parque_id"].value_counts() # Comprobar num de parques y paneles

parque_id
Eugene    473348
Cocoa     421664
Golden    130587
Name: count, dtype: int64

In [3]:
dataset_total["panel_id"].nunique()

22

In [4]:
sorted(dataset_total["panel_id"].unique())

['CIGS1-001_cleaned',
 'CIGS39013_cleaned',
 'CIGS39017_cleaned',
 'CIGS8-001_cleaned',
 'CdTe75638_cleaned',
 'CdTe75669_cleaned',
 'HIT05662_cleaned',
 'HIT05667_cleaned',
 'aSiMicro03036_cleaned',
 'aSiMicro03038_cleaned',
 'aSiTandem72-46_cleaned',
 'aSiTandem90-31_cleaned',
 'aSiTriple28324_cleaned',
 'aSiTriple28325_cleaned',
 'mSi0166_cleaned',
 'mSi0188_cleaned',
 'mSi0247_cleaned',
 'mSi0251_cleaned',
 'mSi460A8_cleaned',
 'mSi460BB_cleaned',
 'xSi11246_cleaned',
 'xSi12922_cleaned']

In [5]:
pd.crosstab(dataset_total["parque_id"], dataset_total["panel_id"])

panel_id,CIGS1-001_cleaned,CIGS39013_cleaned,CIGS39017_cleaned,CIGS8-001_cleaned,CdTe75638_cleaned,CdTe75669_cleaned,HIT05662_cleaned,HIT05667_cleaned,aSiMicro03036_cleaned,aSiMicro03038_cleaned,...,aSiTriple28324_cleaned,aSiTriple28325_cleaned,mSi0166_cleaned,mSi0188_cleaned,mSi0247_cleaned,mSi0251_cleaned,mSi460A8_cleaned,mSi460BB_cleaned,xSi11246_cleaned,xSi12922_cleaned
parque_id,,,,,,,,,,,,,,,,,,,,,
Cocoa,0,0,34775,38939,39080,0,0,38377,39037,0,...,38485,0,36765,39102,0,0,38929,0,0,38989
Eugene,0,0,42674,43146,42248,0,0,43271,43343,0,...,42705,0,43268,43127,0,0,43115,0,0,43185
Golden,12011,11437,0,0,0,11953,11876,0,0,12148,...,0,11445,0,0,11912,11887,0,11919,11929,0

In [6]:
dataset_total.isna().sum()

parque_id                                     0
panel_id                                      0
POA irradiance CMP22 pyranometer (W/m2)       0
PV module back surface temperature (degC)     0
Pmp (W)                                       0
Dry bulb temperature (degC)                   0
Relative humidity (%RH)                       0
Atmospheric pressure (mb)                     0
Precipitation (mm) accumulated daily total    0
Direct normal irradiance (W/m2)               0
Global horizontal irradiance (W/m2)           0
Diffuse horizontal irradiance (W/m2)          0
dtype: int64

# 3. MODELO BASELINE

No ignoramos el parque y el panel, solo el timestamp.

In [7]:
from sklearn.preprocessing import LabelEncoder

le_parque = LabelEncoder()
le_panel  = LabelEncoder()

dataset_total["parque_enc"] = le_parque.fit_transform(dataset_total["parque_id"])
dataset_total["panel_enc"]  = le_panel.fit_transform(dataset_total["panel_id"])

In [8]:
df_model = dataset_total.drop(columns=["parque_id", "panel_id"])

In [9]:
X = df_model.drop(columns=["Pmp (W)"])
y = df_model["Pmp (W)"]

In [10]:
from sklearn.model_selection import train_test_split

# Primero separar test (20%)
X_train_val, X_test, y_train_val, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Luego separar val del resto (20% del total = 25% de train_val)
X_train, X_val, y_train, y_val = train_test_split(
    X_train_val, y_train_val, test_size=0.25, random_state=42
)

# Resultado: 60% train, 20% val, 20% test
print(X_train.shape, X_val.shape, X_test.shape)

(615359, 11) (205120, 11) (205120, 11)

In [11]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_val_scaled = scaler.fit_transform(X_val)
X_test_scaled = scaler.transform(X_test)

In [12]:
import numpy as np

np.mean(X_train_scaled, axis=0)

array([ 1.00041476e-16, -2.15324728e-16, -1.34866625e-17,  1.27476673e-17,
       -2.12461122e-18, -7.57470086e-18,  2.47563394e-17,  1.30247905e-17,
       -8.82175527e-18,  7.84258662e-17,  1.85672545e-17])

In [13]:
np.std(X_train_scaled, axis=0)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
import torch

X_train_tensor = torch.tensor(X_train_scaled, dtype=torch.float32)
X_val_tensor = torch.tensor(X_val_scaled, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test_scaled, dtype=torch.float32)

y_train_tensor = torch.tensor(y_train.values, dtype=torch.float32).view(-1,1)
y_val_tensor = torch.tensor(y_val.values, dtype=torch.float32).view(-1,1)
y_test_tensor = torch.tensor(y_test.values, dtype=torch.float32).view(-1,1)

## A. DISEÑO DEL MODELO

In [15]:
import torch
import torch.nn as nn

class PVModel(nn.Module):
    
    def __init__(self):
        super().__init__()
        
        self.model = nn.Sequential(
            nn.Linear(11, 64),
            nn.ReLU(),
            
            nn.Linear(64, 32),
            nn.ReLU(),
            
            nn.Linear(32, 16),
            nn.ReLU(),
            
            nn.Linear(16, 1)
        )
        
    def forward(self, x):
        return self.model(x)

In [16]:
class PVModelV2(nn.Module):
    
    def __init__(self, input_size=11):
        super().__init__()
        
        self.model = nn.Sequential(
            nn.Linear(input_size, 64),
            nn.BatchNorm1d(64),
            nn.ReLU(),
            nn.Dropout(0.2),
            
            nn.Linear(64, 32),
            nn.BatchNorm1d(32),
            nn.ReLU(),
            nn.Dropout(0.2),
            
            nn.Linear(32, 16),
            nn.BatchNorm1d(16),
            nn.ReLU(),
            nn.Dropout(0.2),
            
            nn.Linear(16, 1)
        )
        
    def forward(self, x):
        return self.model(x)

In [17]:
model = PVModel()
print(model)

model2 = PVModelV2()
print(model2)

PVModel(
  (model): Sequential(
    (0): Linear(in_features=11, out_features=64, bias=True)
    (1): ReLU()
    (2): Linear(in_features=64, out_features=32, bias=True)
    (3): ReLU()
    (4): Linear(in_features=32, out_features=16, bias=True)
    (5): ReLU()
    (6): Linear(in_features=16, out_features=1, bias=True)
  )
)
PVModelV2(
  (model): Sequential(
    (0): Linear(in_features=11, out_features=64, bias=True)
    (1): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): ReLU()
    (3): Dropout(p=0.2, inplace=False)
    (4): Linear(in_features=64, out_features=32, bias=True)
    (5): BatchNorm1d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (6): ReLU()
    (7): Dropout(p=0.2, inplace=False)
    (8): Linear(in_features=32, out_features=16, bias=True)
    (9): BatchNorm1d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (10): ReLU()
    (11): Dropout(p=0.2, inplace=False)
    (12): Linear(in_features=16, out_features=1, bias=True)
  )
)

In [18]:
model(X_train_tensor[:5])

tensor([[0.2450],
        [0.2371],
        [0.2393],
        [0.2379],
        [0.2391]], grad_fn=<AddmmBackward0>)

In [19]:
model2(X_train_tensor[:5])

tensor([[-0.3556],
        [ 1.4632],
        [ 0.7080],
        [ 0.0247],
        [ 0.4426]], grad_fn=<AddmmBackward0>)

In [20]:
criterion = nn.MSELoss()

optimizer = torch.optim.Adam(
    model.parameters(),
    lr=0.001
)

In [21]:
from torch.utils.data import TensorDataset, DataLoader

train_dataset = TensorDataset(X_train_tensor, y_train_tensor)
val_dataset = TensorDataset(X_val_tensor, y_val_tensor)
test_dataset = TensorDataset(X_test_tensor, y_test_tensor)

train_loader = DataLoader(
    train_dataset,
    batch_size=1024,
    shuffle=True
)

val_loader = DataLoader(
    val_dataset,
    batch_size=1024
)

test_loader = DataLoader(
    test_dataset,
    batch_size=1024
)

## B. ML FLOW

In [22]:
import mlflow

In [23]:
mlflow.set_tracking_uri("file:./mlruns")
mlflow.set_experiment("PV_Power")

c:\Users\libeb\OneDrive\Documentos\GitHub\Reto3_MicroRedes\.venv\Lib\site-packages\mlflow\tracking\_tracking_service\utils.py:184: FutureWarning: The filesystem tracking backend (e.g., './mlruns') is deprecated as of February 2026. Consider transitioning to a database backend (e.g., 'sqlite:///mlflow.db') to take advantage of the latest MLflow features. See https://mlflow.org/docs/latest/self-hosting/migrate-from-file-store for migration guidance.
  return FileStore(store_uri, store_uri)
WARNING:root:Malformed experiment '427506226560148484'. Detailed error Yaml file '.\mlruns\427506226560148484\meta.yaml' does not exist.
Traceback (most recent call last):
  File "c:\Users\libeb\OneDrive\Documentos\GitHub\Reto3_MicroRedes\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 383, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\libeb\OneDrive\Documentos\GitHub\Reto3_MicroRedes\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 481, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\libeb\OneDrive\Documentos\GitHub\Reto3_MicroRedes\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1670, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\libeb\OneDrive\Documentos\GitHub\Reto3_MicroRedes\.venv\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1663, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\libeb\OneDrive\Documentos\GitHub\Reto3_MicroRedes\.venv\Lib\site-packages\mlflow\utils\yaml_utils.py", line 104, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file '.\mlruns\427506226560148484\meta.yaml' does not exist.

<Experiment: artifact_location='file:c:/Users/libeb/OneDrive/Documentos/GitHub/Reto3_MicroRedes/OBJETIVO2/mlruns/542888792710679087', creation_time=1774084520213, experiment_id='542888792710679087', last_update_time=1774084520213, lifecycle_stage='active', name='PV_Power', tags={}, workspace='default'>

In [25]:
class PVModel(nn.Module):
    
    def __init__(self, layers_sizes, input_size=11):
        super().__init__()
        
        layers = []
        
        for size in layers_sizes:
            layers.append(nn.Linear(input_size, size))
            layers.append(nn.ReLU())
            input_size = size
        
        layers.append(nn.Linear(input_size, 1))
        
        self.model = nn.Sequential(*layers)
        
    def forward(self, x):
        return self.model(x)

In [26]:
class PVModelV2(nn.Module):
    
    def __init__(self, layers_sizes,dropout, input_size=11):
        super().__init__()
        
        layers = []
        
        for size in layers_sizes:
            layers.append(nn.Linear(input_size, size))
            layers.append(nn.BatchNorm1d(size))   # nuevo
            layers.append(nn.ReLU())
            layers.append(nn.Dropout(dropout))         # nuevo
            input_size = size
        
        layers.append(nn.Linear(input_size, 1))
        
        self.model = nn.Sequential(*layers)
        
    def forward(self, x):
        return self.model(x)

In [27]:
def evaluate(model, loader, criterion):
    
    model.eval()
    total_loss = 0
    
    with torch.no_grad():
        for X_batch, y_batch in loader:
            y_pred = model(X_batch)
            loss = criterion(y_pred, y_batch)
            total_loss += loss.item()
    
    return total_loss / len(loader)

In [28]:
def train_model(arch, lr, epochs, model,dropout=0):
    criterion = nn.MSELoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=lr)

    best_val_loss = float("inf")
    patience = 5
    counter = 0
    
    with mlflow.start_run():
    
        mlflow.log_param("arquitectura", str(arch))
        mlflow.log_param("lr", lr)
        mlflow.log_param("dropout",dropout)
        for epoch in range(epochs):
            
            model.train()
            total_loss = 0
            
            for X_batch, y_batch in train_loader:
                
                y_pred = model(X_batch)
                loss = criterion(y_pred, y_batch)
                
                optimizer.zero_grad()
                loss.backward()
                optimizer.step()
                
                total_loss += loss.item()
            
            train_loss = total_loss / len(train_loader)
            val_loss = evaluate(model, val_loader, criterion)
            
            mlflow.log_metric("train_loss", train_loss, step=epoch)
            mlflow.log_metric("val_loss", val_loss, step=epoch)
            
            print(f"Epoch {epoch+1} | Train: {train_loss:.2f} | Val: {val_loss:.2f}")

            # Early stopping
            if val_loss < best_val_loss:
                best_val_loss = val_loss
                torch.save(model.state_dict(), f"best_model.pt")
                counter = 0
            else:
                counter += 1
            if counter >= patience:
                print(f"Early stopping en epoch {epoch+1}")
                break

    return model

In [29]:
arquitecturas = [
    [64, 32, 16],
    [128, 64, 32],
    [256, 128, 64]
]

learning_rates = [0.001, 0.0005]

dropouts = [0.1, 0.2]

epochs = 100

In [ ]:
for arch in arquitecturas:
    for lr in learning_rates:
        model = PVModel(arch)
        print(f"\nEntrenando modelo {arch} con lr={lr}")
        
        train_model(arch, lr, epochs,model)

Entrenando modelo [64, 32, 16] con lr=0.001
Epoch 1 | Train: 875.12 | Val: 506.08
Epoch 2 | Train: 351.19 | Val: 242.30
Epoch 3 | Train: 193.53 | Val: 154.02
Epoch 4 | Train: 129.81 | Val: 111.18
Epoch 5 | Train: 99.30 | Val: 95.68
Epoch 6 | Train: 83.32 | Val: 80.86
Epoch 7 | Train: 73.16 | Val: 69.75
Epoch 8 | Train: 66.23 | Val: 66.24
Epoch 9 | Train: 61.42 | Val: 58.92
Epoch 10 | Train: 54.17 | Val: 51.01
Epoch 11 | Train: 48.65 | Val: 47.44
Epoch 12 | Train: 45.30 | Val: 43.13
Epoch 13 | Train: 41.88 | Val: 41.51
Epoch 14 | Train: 38.56 | Val: 36.45
Epoch 15 | Train: 35.60 | Val: 33.96
Epoch 16 | Train: 32.98 | Val: 31.54
Epoch 17 | Train: 31.02 | Val: 30.04
Epoch 18 | Train: 29.22 | Val: 28.87
Epoch 19 | Train: 27.89 | Val: 28.08
Epoch 20 | Train: 26.47 | Val: 24.71
Epoch 21 | Train: 25.02 | Val: 26.00
Epoch 22 | Train: 23.67 | Val: 23.73
Epoch 23 | Train: 22.79 | Val: 24.59
Epoch 24 | Train: 22.00 | Val: 21.97
Epoch 25 | Train: 21.19 | Val: 20.59
Epoch 26 | Train: 20.65 | Val: 20.02
Epoch 27 | Train: 19.91 | Val: 21.12
Epoch 28 | Train: 19.31 | Val: 18.63
Epoch 29 | Train: 18.64 | Val: 18.11
Epoch 30 | Train: 17.86 | Val: 18.51
Epoch 31 | Train: 17.26 | Val: 16.18
Epoch 32 | Train: 17.13 | Val: 17.23
Epoch 33 | Train: 16.41 | Val: 18.05
Epoch 34 | Train: 16.13 | Val: 15.35
Epoch 35 | Train: 15.52 | Val: 16.54
Epoch 36 | Train: 15.20 | Val: 16.33
Epoch 37 | Train: 15.14 | Val: 16.47
Epoch 38 | Train: 14.71 | Val: 14.01
Epoch 39 | Train: 14.24 | Val: 15.04
Epoch 40 | Train: 14.07 | Val: 13.76
Epoch 41 | Train: 13.58 | Val: 14.78
Epoch 42 | Train: 13.41 | Val: 12.59
Epoch 43 | Train: 13.29 | Val: 13.37
Epoch 44 | Train: 12.81 | Val: 12.57
Epoch 45 | Train: 12.65 | Val: 12.98
Epoch 46 | Train: 12.52 | Val: 12.43
Epoch 47 | Train: 12.20 | Val: 11.96
Epoch 48 | Train: 12.11 | Val: 12.55
Epoch 49 | Train: 11.86 | Val: 12.49
Epoch 50 | Train: 11.77 | Val: 12.24
Epoch 51 | Train: 11.55 | Val: 13.40
Epoch 52 | Train: 11.41 | Val: 12.23
Early stopping en epoch 52

Entrenando modelo [64, 32, 16] con lr=0.0005
Epoch 1 | Train: 1028.23 | Val: 549.03
Epoch 2 | Train: 513.77 | Val: 473.83
Epoch 3 | Train: 391.54 | Val: 316.00
Epoch 4 | Train: 256.69 | Val: 210.42
Epoch 5 | Train: 177.27 | Val: 150.04
Epoch 6 | Train: 126.63 | Val: 108.71
Epoch 7 | Train: 93.83 | Val: 83.26
Epoch 8 | Train: 75.51 | Val: 69.74
Epoch 9 | Train: 65.07 | Val: 61.39
Epoch 10 | Train: 57.46 | Val: 55.79
Epoch 11 | Train: 51.54 | Val: 49.06
Epoch 12 | Train: 46.36 | Val: 44.73
Epoch 13 | Train: 41.50 | Val: 39.01
Epoch 14 | Train: 37.08 | Val: 34.77
Epoch 15 | Train: 33.00 | Val: 31.40
Epoch 16 | Train: 29.21 | Val: 27.56
Epoch 17 | Train: 25.78 | Val: 24.33
Epoch 18 | Train: 22.82 | Val: 21.50
Epoch 19 | Train: 20.58 | Val: 19.73
Epoch 20 | Train: 18.39 | Val: 17.53
Epoch 21 | Train: 16.21 | Val: 15.37
Epoch 22 | Train: 13.96 | Val: 12.94
Epoch 23 | Train: 11.63 | Val: 10.67
Epoch 24 | Train: 9.75 | Val: 9.50
Epoch 25 | Train: 8.44 | Val: 8.04
Epoch 26 | Train: 7.45 | Val: 7.00
Epoch 27 | Train: 6.73 | Val: 6.64
Epoch 28 | Train: 6.17 | Val: 5.97
Epoch 29 | Train: 5.51 | Val: 5.93
Epoch 30 | Train: 5.32 | Val: 5.55
Epoch 31 | Train: 4.95 | Val: 5.13
Epoch 32 | Train: 4.76 | Val: 4.84
Epoch 33 | Train: 4.57 | Val: 5.01
Epoch 34 | Train: 4.43 | Val: 4.81
Epoch 35 | Train: 4.25 | Val: 4.58
Epoch 36 | Train: 4.08 | Val: 4.30
Epoch 37 | Train: 4.01 | Val: 4.27
Epoch 38 | Train: 3.86 | Val: 3.90
Epoch 39 | Train: 3.83 | Val: 4.73
Epoch 40 | Train: 3.72 | Val: 4.02
Epoch 41 | Train: 3.63 | Val: 3.83
Epoch 42 | Train: 3.57 | Val: 3.82
Epoch 43 | Train: 3.50 | Val: 4.12
Epoch 44 | Train: 3.51 | Val: 4.05
Epoch 45 | Train: 3.43 | Val: 3.79
Epoch 46 | Train: 3.42 | Val: 3.70
Epoch 47 | Train: 3.37 | Val: 3.50
Epoch 48 | Train: 3.36 | Val: 3.78
Epoch 49 | Train: 3.25 | Val: 3.50
Epoch 50 | Train: 3.26 | Val: 3.50
Epoch 51 | Train: 3.21 | Val: 3.67
Epoch 52 | Train: 3.17 | Val: 3.42
Epoch 53 | Train: 3.21 | Val: 3.57
Epoch 54 | Train: 3.14 | Val: 3.37
Epoch 55 | Train: 3.12 | Val: 3.51
Epoch 56 | Train: 3.09 | Val: 3.60
Epoch 57 | Train: 3.07 | Val: 3.50
Epoch 58 | Train: 3.05 | Val: 3.25
Epoch 59 | Train: 3.01 | Val: 3.47
Epoch 60 | Train: 3.00 | Val: 3.15
Epoch 61 | Train: 3.03 | Val: 3.21
Epoch 62 | Train: 2.97 | Val: 3.18
Epoch 63 | Train: 2.91 | Val: 3.14
Epoch 64 | Train: 2.96 | Val: 3.53
Epoch 65 | Train: 2.94 | Val: 3.02
Epoch 66 | Train: 2.88 | Val: 3.21
Epoch 67 | Train: 2.89 | Val: 3.22
Epoch 68 | Train: 2.85 | Val: 2.93
Epoch 69 | Train: 2.84 | Val: 3.14
Epoch 70 | Train: 2.78 | Val: 3.06
Epoch 71 | Train: 2.84 | Val: 3.04
Epoch 72 | Train: 2.77 | Val: 3.51
Epoch 73 | Train: 2.78 | Val: 2.96
Early stopping en epoch 73

Entrenando modelo [128, 64, 32] con lr=0.001
Epoch 1 | Train: 704.86 | Val: 365.59
Epoch 2 | Train: 230.08 | Val: 139.41
Epoch 3 | Train: 98.25 | Val: 70.40
Epoch 4 | Train: 55.49 | Val: 42.28
Epoch 5 | Train: 33.88 | Val: 26.97
Epoch 6 | Train: 21.64 | Val: 17.10
Epoch 7 | Train: 15.10 | Val: 12.71
Epoch 8 | Train: 11.30 | Val: 9.43
Epoch 9 | Train: 8.72 | Val: 6.88
Epoch 10 | Train: 7.04 | Val: 10.40
Epoch 11 | Train: 6.40 | Val: 8.52
Epoch 12 | Train: 5.87 | Val: 4.89
Epoch 13 | Train: 5.47 | Val: 4.84
Epoch 14 | Train: 5.08 | Val: 5.32
Epoch 15 | Train: 4.93 | Val: 4.12
Epoch 16 | Train: 4.85 | Val: 3.90
Epoch 17 | Train: 4.63 | Val: 4.65
Epoch 18 | Train: 4.17 | Val: 4.34
Epoch 19 | Train: 4.36 | Val: 4.75
Epoch 20 | Train: 3.83 | Val: 5.15
Epoch 21 | Train: 3.63 | Val: 5.93
Early stopping en epoch 21

Entrenando modelo [128, 64, 32] con lr=0.0005
Epoch 1 | Train: 833.77 | Val: 471.14
Epoch 2 | Train: 350.43 | Val: 274.58
Epoch 3 | Train: 227.45 | Val: 187.46
Epoch 4 | Train: 151.21 | Val: 122.71
Epoch 5 | Train: 100.80 | Val: 86.05
Epoch 6 | Train: 75.97 | Val: 68.78
Epoch 7 | Train: 62.40 | Val: 60.94
Epoch 8 | Train: 53.94 | Val: 51.48
Epoch 9 | Train: 47.47 | Val: 43.69
Epoch 10 | Train: 42.16 | Val: 40.80
Epoch 11 | Train: 38.00 | Val: 36.87
Epoch 12 | Train: 34.84 | Val: 33.18
Epoch 13 | Train: 32.19 | Val: 30.02
Epoch 14 | Train: 29.86 | Val: 28.87
Epoch 15 | Train: 28.07 | Val: 29.24
Epoch 16 | Train: 26.32 | Val: 24.84
Epoch 17 | Train: 25.03 | Val: 23.40
Epoch 18 | Train: 22.65 | Val: 20.86
Epoch 19 | Train: 21.36 | Val: 19.99
Epoch 20 | Train: 19.83 | Val: 20.06
Epoch 21 | Train: 19.03 | Val: 17.68
Epoch 22 | Train: 17.93 | Val: 16.63
Epoch 23 | Train: 17.00 | Val: 21.37
Epoch 24 | Train: 15.97 | Val: 16.42
Epoch 25 | Train: 15.02 | Val: 14.00
Epoch 26 | Train: 14.59 | Val: 14.14
Epoch 27 | Train: 13.18 | Val: 12.48
Epoch 28 | Train: 12.60 | Val: 12.88
Epoch 29 | Train: 11.87 | Val: 10.90
Epoch 30 | Train: 11.06 | Val: 14.42
Epoch 31 | Train: 10.77 | Val: 9.70
Epoch 32 | Train: 10.43 | Val: 10.05
Epoch 33 | Train: 9.46 | Val: 9.51
Epoch 34 | Train: 9.38 | Val: 10.58
Epoch 35 | Train: 8.78 | Val: 9.90
Epoch 36 | Train: 8.46 | Val: 8.06
Epoch 37 | Train: 7.93 | Val: 8.36
Epoch 38 | Train: 7.72 | Val: 7.91
Epoch 39 | Train: 7.23 | Val: 8.59
Epoch 40 | Train: 7.15 | Val: 6.93
Epoch 41 | Train: 6.66 | Val: 7.86
Epoch 42 | Train: 6.61 | Val: 8.69
Epoch 43 | Train: 6.55 | Val: 6.13
Epoch 44 | Train: 6.00 | Val: 6.04
Epoch 45 | Train: 5.98 | Val: 6.67
Epoch 46 | Train: 5.50 | Val: 6.46
Epoch 47 | Train: 5.43 | Val: 6.13
Epoch 48 | Train: 5.19 | Val: 4.94
Epoch 49 | Train: 5.07 | Val: 4.78
Epoch 50 | Train: 4.93 | Val: 4.47
Epoch 51 | Train: 4.75 | Val: 6.72
Epoch 52 | Train: 4.60 | Val: 5.26
Epoch 53 | Train: 4.55 | Val: 4.43
Epoch 54 | Train: 4.48 | Val: 6.11
Epoch 55 | Train: 4.41 | Val: 4.56
Epoch 56 | Train: 4.27 | Val: 4.96
Epoch 57 | Train: 4.23 | Val: 4.54
Epoch 58 | Train: 4.09 | Val: 3.86
Epoch 59 | Train: 3.97 | Val: 4.38
Epoch 60 | Train: 3.98 | Val: 4.02
Epoch 61 | Train: 3.84 | Val: 6.25
Epoch 62 | Train: 3.86 | Val: 5.28
Epoch 63 | Train: 3.78 | Val: 3.77
Epoch 64 | Train: 3.78 | Val: 3.96
Epoch 65 | Train: 3.56 | Val: 4.91
Epoch 66 | Train: 3.69 | Val: 5.05
Epoch 67 | Train: 3.53 | Val: 3.57

In [ ]:
for arch in arquitecturas: 
    for lr in learning_rates:
        model = PVModelV2(arch,dropout=dropouts)
        print(f"\nEntrenando modelo {arch} con lr={lr}")
        train_model(arch, lr, epochs,model)

Entrenando modelo [64, 32, 16] con lr=0.001
Epoch 1 | Train: 1832.45 | Val: 945.68
Epoch 2 | Train: 430.07 | Val: 129.97
Epoch 3 | Train: 198.07 | Val: 75.97
Epoch 4 | Train: 180.36 | Val: 65.86
Epoch 5 | Train: 167.48 | Val: 59.71
Epoch 6 | Train: 159.62 | Val: 51.52
Epoch 7 | Train: 152.91 | Val: 50.32
Epoch 8 | Train: 148.05 | Val: 38.20
Epoch 9 | Train: 142.65 | Val: 44.38
Epoch 10 | Train: 139.12 | Val: 36.93
Epoch 11 | Train: 137.75 | Val: 37.81
Epoch 12 | Train: 134.73 | Val: 30.48
Epoch 13 | Train: 133.75 | Val: 32.84
Epoch 14 | Train: 131.86 | Val: 33.62
Epoch 15 | Train: 127.49 | Val: 38.22
Epoch 16 | Train: 129.71 | Val: 34.14
Epoch 17 | Train: 127.42 | Val: 26.56
Epoch 18 | Train: 128.06 | Val: 31.90
Epoch 19 | Train: 124.44 | Val: 25.10
Epoch 20 | Train: 125.22 | Val: 29.10
Epoch 21 | Train: 122.50 | Val: 30.67
Epoch 22 | Train: 123.23 | Val: 29.46
Epoch 23 | Train: 120.21 | Val: 26.58
Epoch 24 | Train: 120.61 | Val: 26.08
Early stopping en epoch 24

Entrenando modelo [64, 32, 16] con lr=0.0005
Epoch 1 | Train: 115.77 | Val: 25.72
Epoch 2 | Train: 113.49 | Val: 23.08
Epoch 3 | Train: 115.48 | Val: 22.98
Epoch 4 | Train: 112.82 | Val: 23.80
Epoch 5 | Train: 113.93 | Val: 24.72
Epoch 6 | Train: 113.87 | Val: 25.21
Epoch 7 | Train: 113.45 | Val: 26.72
Epoch 8 | Train: 113.17 | Val: 27.47
Early stopping en epoch 8

Entrenando modelo [128, 64, 32] con lr=0.001
Epoch 1 | Train: 1436.36 | Val: 336.51
Epoch 2 | Train: 225.09 | Val: 75.77
Epoch 3 | Train: 147.73 | Val: 58.67
Epoch 4 | Train: 126.49 | Val: 37.58
Epoch 5 | Train: 111.90 | Val: 27.19
Epoch 6 | Train: 99.63 | Val: 18.92
Epoch 7 | Train: 92.42 | Val: 20.39
Epoch 8 | Train: 87.42 | Val: 19.07
Epoch 9 | Train: 82.20 | Val: 14.86
Epoch 10 | Train: 79.51 | Val: 15.69
Epoch 11 | Train: 75.60 | Val: 12.25
Epoch 12 | Train: 75.95 | Val: 10.65
Epoch 13 | Train: 73.23 | Val: 9.80
Epoch 14 | Train: 70.03 | Val: 7.74
Epoch 15 | Train: 69.15 | Val: 10.31
Epoch 16 | Train: 68.81 | Val: 9.12
Epoch 17 | Train: 65.76 | Val: 10.78
Epoch 18 | Train: 66.68 | Val: 9.19
Epoch 19 | Train: 63.20 | Val: 9.02
Early stopping en epoch 19

Entrenando modelo [128, 64, 32] con lr=0.0005
Epoch 1 | Train: 61.32 | Val: 8.57
Epoch 2 | Train: 62.85 | Val: 6.31
Epoch 3 | Train: 61.11 | Val: 7.60
Epoch 4 | Train: 59.91 | Val: 6.97
Epoch 5 | Train: 58.43 | Val: 7.92
Epoch 6 | Train: 60.09 | Val: 5.93
Epoch 7 | Train: 60.77 | Val: 5.91
Epoch 8 | Train: 61.36 | Val: 5.97
Epoch 9 | Train: 58.38 | Val: 5.55
Epoch 10 | Train: 59.33 | Val: 7.08
Epoch 11 | Train: 58.17 | Val: 7.85
Epoch 12 | Train: 57.34 | Val: 6.57
Epoch 13 | Train: 57.34 | Val: 9.30
Epoch 14 | Train: 57.97 | Val: 5.07
Epoch 15 | Train: 57.33 | Val: 4.34
Epoch 16 | Train: 55.78 | Val: 6.12
Epoch 17 | Train: 58.30 | Val: 6.20
Epoch 18 | Train: 56.24 | Val: 8.23
Epoch 19 | Train: 56.39 | Val: 5.20
Epoch 20 | Train: 55.69 | Val: 6.30
Early stopping en epoch 20

Entrenando modelo [256, 128, 64] con lr=0.001
Epoch 1 | Train: 1057.11 | Val: 123.46
Epoch 2 | Train: 158.77 | Val: 60.58
Epoch 3 | Train: 115.67 | Val: 46.21
Epoch 4 | Train: 96.93 | Val: 27.92
Epoch 5 | Train: 82.34 | Val: 23.34
Epoch 6 | Train: 70.82 | Val: 19.24
Epoch 7 | Train: 64.91 | Val: 12.77
Epoch 8 | Train: 59.07 | Val: 11.20
Epoch 9 | Train: 56.32 | Val: 10.23
Epoch 10 | Train: 52.84 | Val: 12.30
Epoch 11 | Train: 49.67 | Val: 7.87
Epoch 12 | Train: 48.99 | Val: 9.70
Epoch 13 | Train: 48.85 | Val: 6.23
Epoch 14 | Train: 44.66 | Val: 5.12
Epoch 15 | Train: 42.92 | Val: 9.66
Epoch 16 | Train: 41.17 | Val: 7.29
Epoch 17 | Train: 41.99 | Val: 7.53
Epoch 18 | Train: 39.26 | Val: 5.70
Epoch 19 | Train: 40.94 | Val: 5.70
Early stopping en epoch 19

Entrenando modelo [256, 128, 64] con lr=0.0005
Epoch 1 | Train: 35.55 | Val: 4.96
Epoch 2 | Train: 35.86 | Val: 4.99
Epoch 3 | Train: 33.77 | Val: 5.00
Epoch 4 | Train: 33.53 | Val: 4.48
Epoch 5 | Train: 36.14 | Val: 5.26
Epoch 6 | Train: 34.47 | Val: 4.18
Epoch 7 | Train: 33.24 | Val: 3.91
Epoch 8 | Train: 34.17 | Val: 5.43
Epoch 9 | Train: 35.33 | Val: 4.62
Epoch 10 | Train: 32.56 | Val: 3.51
Epoch 11 | Train: 32.84 | Val: 3.90
Epoch 12 | Train: 32.66 | Val: 3.11
Epoch 13 | Train: 31.88 | Val: 3.76
Epoch 14 | Train: 32.27 | Val: 3.30
Epoch 15 | Train: 31.33 | Val: 3.73
Epoch 16 | Train: 31.21 | Val: 5.23
Epoch 17 | Train: 31.99 | Val: 2.69
Epoch 18 | Train: 30.69 | Val: 3.79
Epoch 19 | Train: 32.05 | Val: 3.97
Epoch 20 | Train: 31.11 | Val: 4.02
Epoch 21 | Train: 31.01 | Val: 3.66
Epoch 22 | Train: 29.57 | Val: 2.70
Early stopping en epoch 22

# MODELOS SIMPLES

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# Entrenar modelo
lr_model = LinearRegression()
lr_model.fit(X_train, y_train)

# Predicción
y_pred = lr_model.predict(X_val)

# Métricas
mse = mean_squared_error(y_val, y_pred)
rmse = mse ** 0.5
r2 = r2_score(y_val, y_pred)

print("MSE:", mse)
print("RMSE:", rmse)
print("R2:", r2)

MSE: 576.3045725256211
RMSE: 24.006344422373456
R2: 0.5934330172716631

In [ ]:
y_pred_nn = model(X_val_tensor).detach().numpy()

In [ ]:
mean_squared_error(y_val, y_pred_nn)

2.7023941642793217

In [ ]:
from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error, r2_score

# Modelo
model = XGBRegressor(
    n_estimators=300,
    max_depth=5,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

# Entrenar
model.fit(X_train, y_train)

# Predecir
y_pred = model.predict(X_val)

# Métricas
mse = mean_squared_error(y_val, y_pred)
rmse = mse ** 0.5
r2 = r2_score(y_val, y_pred)

print("MSE:", mse)
print("RMSE:", rmse)
print("R2:", r2)

MSE: 2.490038629218615
RMSE: 1.5779856238947854
R2: 0.9982433464167709

# 4. FEATURE ENGENIERING

In [ ]:
corr = df_model.corr(numeric_only=True)
corr["Pmp (W)"].sort_values(ascending=False)

Pmp (W)                                       1.000000
POA irradiance CMP22 pyranometer (W/m2)       0.748333
PV module back surface temperature (degC)     0.561800
Direct normal irradiance (W/m2)               0.068805
Global horizontal irradiance (W/m2)           0.057096
Precipitation (mm) accumulated daily total   -0.018312
Dry bulb temperature (degC)                  -0.019508
Diffuse horizontal irradiance (W/m2)         -0.023923
Atmospheric pressure (mb)                    -0.031497
Relative humidity (%RH)                      -0.033575
parque_enc                                   -0.036538
panel_enc                                    -0.179015
Name: Pmp (W), dtype: float64

In [ ]:
df_model["physical_model"] = (
    df_model["POA irradiance CMP22 pyranometer (W/m2)"] *
    (1 - 0.004 * (df_model["PV module back surface temperature (degC)"] - 25))
)

In [ ]:
df_model = df_model[[
    "POA irradiance CMP22 pyranometer (W/m2)",
    "PV module back surface temperature (degC)",
    "physical_model",
    "Pmp (W)"
]]

In [ ]:
X = df_model.drop(columns=["Pmp (W)"])
y = df_model["Pmp (W)"]

In [ ]:
from sklearn.model_selection import train_test_split

# Primero separar test (20%)
X_train_val, X_test, y_train_val, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Luego separar val del resto (20% del total = 25% de train_val)
X_train, X_val, y_train, y_val = train_test_split(
    X_train_val, y_train_val, test_size=0.25, random_state=42
)

# Resultado: 60% train, 20% val, 20% test
print(X_train.shape, X_val.shape, X_test.shape)

(615359, 3) (205120, 3) (205120, 3)

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_val_scaled = scaler.fit_transform(X_val)
X_test_scaled = scaler.transform(X_test)

In [ ]:
from torch.utils.data import TensorDataset, DataLoader

train_dataset = TensorDataset(X_train_tensor, y_train_tensor)
val_dataset = TensorDataset(X_val_tensor, y_val_tensor)
test_dataset = TensorDataset(X_test_tensor, y_test_tensor)

train_loader = DataLoader(
    train_dataset,
    batch_size=1024,
    shuffle=True
)

val_loader = DataLoader(
    val_dataset,
    batch_size=1024,
    shuffle=True
)

test_loader = DataLoader(
    test_dataset,
    batch_size=1024
)

In [ ]:
for arch in arquitecturas:
    for lr in learning_rates:
        model = PVModel(arch)
        print(f"\nEntrenando modelo {arch} con lr={lr}")
        train_model(arch, lr, epochs,model)

Entrenando modelo [64, 32, 16] con lr=0.001
Epoch 1 | Train: 783.75 | Val: 440.72
Epoch 2 | Train: 298.80 | Val: 185.69
Epoch 3 | Train: 144.22 | Val: 113.72
Epoch 4 | Train: 94.83 | Val: 82.66
Epoch 5 | Train: 67.27 | Val: 61.18
Epoch 6 | Train: 49.45 | Val: 42.40
Epoch 7 | Train: 36.00 | Val: 31.09
Epoch 8 | Train: 25.44 | Val: 20.71
Epoch 9 | Train: 17.92 | Val: 14.90
Epoch 10 | Train: 13.23 | Val: 11.03
Epoch 11 | Train: 10.40 | Val: 9.97
Epoch 12 | Train: 8.58 | Val: 7.54
Epoch 13 | Train: 7.25 | Val: 7.47
Epoch 14 | Train: 6.36 | Val: 5.68
Epoch 15 | Train: 5.59 | Val: 4.94
Epoch 16 | Train: 4.84 | Val: 4.48
Epoch 17 | Train: 4.36 | Val: 3.77
Epoch 18 | Train: 3.82 | Val: 3.83
Epoch 19 | Train: 3.44 | Val: 3.62
Epoch 20 | Train: 3.29 | Val: 3.21
Epoch 21 | Train: 3.05 | Val: 3.24
Epoch 22 | Train: 3.00 | Val: 2.76
Epoch 23 | Train: 2.85 | Val: 3.02
Epoch 24 | Train: 2.65 | Val: 2.79
Epoch 25 | Train: 2.60 | Val: 2.64
Epoch 26 | Train: 2.58 | Val: 2.96
Epoch 27 | Train: 2.45 | Val: 3.07
Epoch 28 | Train: 2.44 | Val: 2.76
Epoch 29 | Train: 2.43 | Val: 2.42
Epoch 30 | Train: 2.35 | Val: 2.62
Epoch 31 | Train: 2.38 | Val: 2.58
Epoch 32 | Train: 2.32 | Val: 2.49
Epoch 33 | Train: 2.24 | Val: 2.49
Epoch 34 | Train: 2.30 | Val: 2.54
Early stopping en epoch 34

Entrenando modelo [64, 32, 16] con lr=0.0005
Epoch 1 | Train: 2.08 | Val: 2.20
Epoch 2 | Train: 2.03 | Val: 2.16
Epoch 3 | Train: 2.03 | Val: 2.23
Epoch 4 | Train: 2.00 | Val: 2.32
Epoch 5 | Train: 1.97 | Val: 2.02
Epoch 6 | Train: 1.98 | Val: 2.26
Epoch 7 | Train: 1.98 | Val: 2.22
Epoch 8 | Train: 2.00 | Val: 2.08
Epoch 9 | Train: 1.92 | Val: 2.26
Epoch 10 | Train: 1.96 | Val: 2.09
Early stopping en epoch 10

Entrenando modelo [128, 64, 32] con lr=0.001
Epoch 1 | Train: 683.49 | Val: 370.75
Epoch 2 | Train: 225.77 | Val: 131.68
Epoch 3 | Train: 93.03 | Val: 63.92
Epoch 4 | Train: 48.68 | Val: 34.35
Epoch 5 | Train: 25.24 | Val: 17.24
Epoch 6 | Train: 14.67 | Val: 10.85
Epoch 7 | Train: 9.93 | Val: 7.87
Epoch 8 | Train: 7.77 | Val: 6.18
Epoch 9 | Train: 5.97 | Val: 5.54
Epoch 10 | Train: 5.07 | Val: 5.93
Epoch 11 | Train: 4.49 | Val: 4.81
Epoch 12 | Train: 4.02 | Val: 3.43
Epoch 13 | Train: 3.71 | Val: 3.94
Epoch 14 | Train: 3.15 | Val: 3.17
Epoch 15 | Train: 2.90 | Val: 3.29
Epoch 16 | Train: 2.89 | Val: 2.87
Epoch 17 | Train: 2.74 | Val: 2.60
Epoch 18 | Train: 2.83 | Val: 3.00
Epoch 19 | Train: 2.48 | Val: 2.67
Epoch 20 | Train: 2.61 | Val: 2.16
Epoch 21 | Train: 2.46 | Val: 2.60
Epoch 22 | Train: 2.38 | Val: 2.45
Epoch 23 | Train: 2.43 | Val: 2.37
Epoch 24 | Train: 2.35 | Val: 2.54
Epoch 25 | Train: 2.39 | Val: 3.25
Early stopping en epoch 25

Entrenando modelo [128, 64, 32] con lr=0.0005
Epoch 1 | Train: 2.06 | Val: 2.54
Epoch 2 | Train: 1.96 | Val: 2.04
Epoch 3 | Train: 1.93 | Val: 2.11
Epoch 4 | Train: 1.92 | Val: 1.94
Epoch 5 | Train: 1.94 | Val: 2.04
Epoch 6 | Train: 1.90 | Val: 2.06

KeyboardInterrupt:

In [ ]:
for arch in arquitecturas:
    for lr in learning_rates:
        model = PVModelV2(arch,dropout=dropouts)
        print(f"\nEntrenando modelo {arch} con lr={lr}")
        train_model(arch, lr, epochs,model)

# ENTRENAMIENTOS FINALES DE LOS MEJORES MODELOS